# Generated by Django 4.1.2 on 2022-12-29 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0002_alter_contractor_tb_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor_tb',
            name='Password',
        ),
        migrations.CreateModel(
            name='Cwork_TB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upload_work', models.ImageField(upload_to='work')),
                ('Sq_feet', models.IntegerField(max_length=50)),
                ('Price', models.IntegerField(max_length=50)),
                ('Description', models.CharField(max_length=100)),
                ('workid', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='contractor.contractor_tb')),
            ],
        ),
    ]
