# Generated by Django 4.1.2 on 2022-12-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0003_remove_contractor_tb_password_cwork_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cwork_tb',
            name='Sq_feet',
        ),
        migrations.AddField(
            model_name='cwork_tb',
            name='Feet',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='cwork_tb',
            name='Price',
            field=models.CharField(max_length=50),
        ),
    ]
