# Generated by Django 4.1.2 on 2022-12-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0004_remove_cwork_tb_sq_feet_cwork_tb_feet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cwork_tb',
            old_name='Upload_work',
            new_name='Workimg',
        ),
    ]
