# Generated by Django 4.1.2 on 2022-12-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0005_rename_upload_work_cwork_tb_workimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwork_tb',
            name='workid',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
