# Generated by Django 4.1.4 on 2023-01-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0006_alter_cwork_tb_workid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwork_tb',
            name='workvid',
            field=models.FileField(default='a.mp4', upload_to='cwork_vid'),
        ),
    ]
