# Generated by Django 4.1.4 on 2023-01-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0007_cwork_tb_workvid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwork_tb',
            name='dislike',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='cwork_tb',
            name='like',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
