# Generated by Django 4.1.4 on 2023-01-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0008_cwork_tb_dislike_cwork_tb_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwork_tb',
            name='dislike',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='cwork_tb',
            name='like',
            field=models.IntegerField(default='0'),
        ),
    ]
