# Generated by Django 4.1.4 on 2023-01-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0011_alter_cwork_tb_dislike_alter_cwork_tb_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwork_tb',
            name='dislike',
            field=models.IntegerField(default='0'),
        ),
    ]
