# Generated by Django 4.1.4 on 2023-01-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0012_alter_cwork_tb_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwork_tb',
            name='like',
            field=models.IntegerField(default='0'),
        ),
    ]
