# Generated by Django 4.1.4 on 2023-01-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0013_alter_cwork_tb_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwork_tb',
            name='userid',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
