# Generated by Django 4.1.4 on 2023-01-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0015_alter_cwork_tb_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwork_tb',
            name='userid',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
