# Generated by Django 4.1.4 on 2023-01-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0016_alter_cwork_tb_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ccomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.CharField(max_length=50)),
                ('to_id', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=50)),
            ],
        ),
    ]
