# Generated by Django 4.1.4 on 2023-01-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0017_ccomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccomment',
            name='time',
            field=models.TimeField(null='True'),
            preserve_default='True',
        ),
    ]
