# Generated by Django 4.1.4 on 2023-01-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0018_ccomment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccomment',
            name='name',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
