# Generated by Django 4.1.2 on 2023-02-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0022_cwork_tb_likeflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwork_tb',
            name='dislikeflag',
            field=models.BooleanField(default='False'),
        ),
    ]
