# Generated by Django 4.1.2 on 2022-12-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer_tb',
            name='Password',
        ),
    ]
