# Generated by Django 4.1.4 on 2023-01-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0005_ework_tb_dislike_ework_tb_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ework_tb',
            name='dislike',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='ework_tb',
            name='like',
            field=models.IntegerField(default='0'),
        ),
    ]
