# Generated by Django 4.1.4 on 2023-01-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0006_alter_ework_tb_dislike_alter_ework_tb_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='ework_tb',
            name='userid',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
