# Generated by Django 4.1.2 on 2022-12-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiordesigner', '0002_remove_designer_tb_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iwork_TB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Workimg', models.ImageField(upload_to='work')),
                ('Feet', models.CharField(default='null', max_length=50)),
                ('Price', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=100)),
                ('workid', models.CharField(default='1', max_length=100)),
            ],
        ),
    ]
