# Generated by Django 4.1.4 on 2023-01-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiordesigner', '0007_iwork_tb_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='user', max_length=50)),
                ('from_id', models.CharField(max_length=50)),
                ('to_id', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=50)),
                ('time', models.DateTimeField(null='True')),
            ],
        ),
    ]
