# Generated by Django 4.1.2 on 2023-02-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_sproduct_tb_workvid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sproduct_tb',
            name='workvid',
        ),
        migrations.AddField(
            model_name='sproduct_tb',
            name='Workvid',
            field=models.FileField(default='a.mp4', upload_to='swork_vid'),
        ),
    ]
