# Generated by Django 4.1.2 on 2022-12-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, unique=True)),
                ('Mobile', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='User')),
                ('Password', models.CharField(max_length=15)),
            ],
        ),
    ]
