# Generated by Django 4.1.2 on 2022-12-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_DB',
            new_name='Registration_TB',
        ),
    ]
