# Generated by Django 4.1.4 on 2023-01-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_db_registration_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages_Tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Messages', models.CharField(max_length=500)),
                ('Date', models.DateField(max_length=10)),
                ('Time', models.TimeField(max_length=50)),
                ('Send_id', models.CharField(max_length=50)),
                ('Receiver_id', models.CharField(max_length=50)),
                ('Send_name', models.CharField(max_length=50)),
                ('Receiver_name', models.CharField(max_length=50)),
            ],
        ),
    ]
