# Generated by Django 4.1.4 on 2023-01-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_messages_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_tb',
            name='usertype',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
