# Generated by Django 4.1.4 on 2023-01-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_registration_tb_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_tb',
            name='accept',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='registration_tb',
            name='reject',
            field=models.BooleanField(default='False'),
        ),
    ]
