# Generated by Django 4.1.2 on 2022-12-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Astroleger_TB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, unique=True)),
                ('Mobile', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Image', models.ImageField(max_length=50, upload_to='')),
                ('Address', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('Place', models.CharField(max_length=50)),
                ('Pincode', models.CharField(max_length=50)),
                ('Qualification', models.ImageField(max_length=50, upload_to='')),
                ('Experience', models.IntegerField(default=2)),
                ('astro_id', models.CharField(default=0, max_length=20)),
                ('Password', models.CharField(max_length=15)),
            ],
        ),
    ]
