# Generated by Django 4.1.2 on 2022-12-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astroleger_tb',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='astroleger_tb',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='astroleger_tb',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='astroleger_tb',
            name='Mobile',
        ),
        migrations.RemoveField(
            model_name='astroleger_tb',
            name='Name',
        ),
        migrations.AlterField(
            model_name='astroleger_tb',
            name='Email',
            field=models.EmailField(default='a@gmail.com', max_length=50),
        ),
    ]
