# Generated by Django 4.1.2 on 2022-12-29 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrologer', '0002_remove_astroleger_tb_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astroleger_tb',
            name='Password',
        ),
    ]
