# Generated by Django 4.1.2 on 2023-01-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologer', '0003_remove_astroleger_tb_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='astroleger_tb',
            name='Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='astroleger_tb',
            name='Travelling',
            field=models.IntegerField(default=0),
        ),
    ]
