# Generated by Django 4.1.4 on 2023-01-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologer', '0004_astroleger_tb_price_astroleger_tb_travelling'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABook_TB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(default='a@gmail.com', max_length=50)),
                ('Number', models.CharField(max_length=50)),
                ('astroid', models.CharField(default='1', max_length=100)),
                ('userid', models.CharField(max_length=50)),
            ],
        ),
    ]
