# Generated by Django 4.1.4 on 2023-01-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologer', '0005_abook_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='abook_tb',
            name='time',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
