# Generated by Django 4.1.4 on 2023-01-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologer', '0007_abook_tb_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='abook_tb',
            name='accept',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='abook_tb',
            name='reject',
            field=models.BooleanField(default='False'),
        ),
    ]
