# Generated by Django 4.1.4 on 2023-01-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologer', '0008_abook_tb_accept_abook_tb_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='abook_tb',
            name='fees',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
