# Generated by Django 4.1.2 on 2023-01-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologer', '0009_abook_tb_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='abook_tb',
            name='date',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
