# Generated by Django 4.1.2 on 2023-02-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologer', '0011_remove_astroleger_tb_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abook_tb',
            name='Address',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='abook_tb',
            name='City',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='abook_tb',
            name='Landmark',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='abook_tb',
            name='Pincode',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
