# Generated by Django 4.1.2 on 2023-02-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologer', '0013_alter_astroleger_tb_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astroleger_tb',
            name='Pincode',
            field=models.CharField(max_length=50),
        ),
    ]
